"""attendance lock

Revision ID: 0eade62a3ea4
Revises: ce40e064a3fb
Create Date: 2026-02-03 22:10:26.458926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eade62a3ea4'
down_revision: Union[str, None] = 'ce40e064a3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.alter_column('attendance', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendance', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance', 'classroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('attendance', 'is_locked')
    # ### end Alembic commands ###
