"""add_attendance_claims

Revision ID: 18427d9913a8
Revises: 287e55d1799c
Create Date: 2026-06-18 19:01:08.104864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '18427d9913a8'
down_revision: Union[str, None] = '287e55d1799c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'attendance_claims',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('attendance_id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column(
            'original_attendance_status',
            postgresql.ENUM(
                'CONFIRMED',
                'FLAGGED',
                'REJECTED',
                name='attendance_status',
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'PENDING',
                'APPROVED',
                'REJECTED',
                name='claim_status',
            ),
            nullable=False,
        ),
        sa.Column('claim_resolved_by', sa.Integer(), nullable=True),
        sa.Column(
            'claim_resolved_at',
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            'claim_resolution_reason',
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['attendance_id'],
            ['attendance.id'],
        ),
        sa.ForeignKeyConstraint(
            ['claim_resolved_by'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['student_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'attendance_id',
            name='uq_claim_attendance',
        ),
    )

    op.create_index(
        op.f('ix_attendance_claims_attendance_id'),
        'attendance_claims',
        ['attendance_id'],
        unique=False,
    )

    op.create_index(
        op.f('ix_attendance_claims_student_id'),
        'attendance_claims',
        ['student_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_attendance_claims_student_id'),
        table_name='attendance_claims',
    )

    op.drop_index(
        op.f('ix_attendance_claims_attendance_id'),
        table_name='attendance_claims',
    )

    op.drop_table('attendance_claims')
    # ### end Alembic commands ###