"""registration requests

Revision ID: 2d162ce3cec5
Revises: d2f53c6d9fff
Create Date: 2026-06-17 02:23:33.339521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d162ce3cec5'
down_revision: Union[str, None] = 'd2f53c6d9fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='registrationrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['course_registration_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_registration_request')
    )
    op.create_index(op.f('ix_course_registration_requests_id'), 'course_registration_requests', ['id'], unique=False)
    op.create_index('ix_registration_request_session_id', 'course_registration_requests', ['session_id'], unique=False)
    op.create_index('ix_registration_request_student_id', 'course_registration_requests', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_registration_request_student_id', table_name='course_registration_requests')
    op.drop_index('ix_registration_request_session_id', table_name='course_registration_requests')
    op.drop_index(op.f('ix_course_registration_requests_id'), table_name='course_registration_requests')
    op.drop_table('course_registration_requests')
    # ### end Alembic commands ###
