"""add_claim_id_to_faculty_logs

Revision ID: 3fb23d62d70b
Revises: 18427d9913a8
Create Date: 2026-06-18 20:38:16.916183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb23d62d70b'
down_revision: Union[str, None] = '18427d9913a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_action_logs', sa.Column('claim_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty_action_logs', 'claim_id')
    # ### end Alembic commands ###
