"""add_unique_constraint_to_classroom_name

Revision ID: 465cb3750ddb
Revises: 3fb23d62d70b
Create Date: 2026-06-19 00:36:09.808429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465cb3750ddb'
down_revision: Union[str, None] = '3fb23d62d70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_classroom_name",
        "classrooms",
        ["name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_classroom_name",
        "classrooms",
        type_="unique",
    )
    # ### end Alembic commands ###