"""add_attendance_gps_evidence

Revision ID: 581304ef2f16
Revises: ffa2c8940924
Create Date: 2026-06-07 13:36:34.558460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581304ef2f16'
down_revision: Union[str, None] = 'ffa2c8940924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_gps_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_meters', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('distance_from_classroom_meters', sa.Float(), nullable=True),
    sa.Column('validation_result', sa.String(length=50), nullable=True),
    sa.Column('validation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_gps_evidence_attendance_id'), 'attendance_gps_evidence', ['attendance_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_gps_evidence_attendance_id'), table_name='attendance_gps_evidence')
    op.drop_table('attendance_gps_evidence')
    # ### end Alembic commands ###
