# backend\alembic\versions\729d4c99f52c_add_classrooms.py
"""add classrooms

Revision ID: 729d4c99f52c
Revises: cf6b9c80dc6d
Create Date: 2026-02-02 23:04:50.420082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "729d4c99f52c"
down_revision: Union[str, None] = "cf6b9c80dc6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Only create classrooms (trimmed unrelated autogen changes: attendance, sessions, enums)
    op.create_table(
        "classrooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("faculty_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["faculty_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(op.f("ix_classrooms_id"), "classrooms", ["id"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("faculty_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.create_foreign_key("sessions_faculty_id_fkey", "sessions", "users", ["faculty_id"], ["id"])
    op.drop_column("sessions", "device_id")
    op.drop_column("sessions", "user_id")
    op.alter_column(
        "attendance",
        "status",
        existing_type=sa.Enum("CONFIRMED", "FLAGGED", name="attendance_status"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_classrooms_id"), table_name="classrooms")
    op.drop_table("classrooms")
    # ### end Alembic commands ###
