"""final_clean_check

Revision ID: 8a3f5d543519
Revises: 5c31ad658b75
Create Date: 2026-06-03 16:59:28.411700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8a3f5d543519"
down_revision: Union[str, None] = "5c31ad658b75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - cleaned safely ###

    op.create_index(
        op.f("ix_attendance_classroom_id"),
        "attendance",
        ["classroom_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_attendance_session_id"),
        "attendance",
        ["session_id"],
        unique=False,
    )

    op.create_index(
        op.f("ix_attendance_student_id"),
        "attendance",
        ["student_id"],
        unique=False,
    )

    op.drop_column("attendance", "is_locked")

    op.create_index(
        op.f("ix_attendance_ble_evidence_attendance_id"),
        "attendance_ble_evidence",
        ["attendance_id"],
        unique=False,
    )

    op.execute(
        """
        UPDATE attendance_sessions
        SET
            expires_at = NOW(),
            duration_minutes = 10
        WHERE
            expires_at IS NULL
            OR duration_minutes IS NULL
        """
    )

    op.alter_column(
        "attendance_sessions",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )

    op.alter_column(
        "attendance_sessions",
        "duration_minutes",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("10"),
    )

    op.create_index(
        "ix_attendance_sessions_classroom_id",
        "attendance_sessions",
        ["classroom_id"],
        unique=False,
    )

    op.create_index(
        "ix_attendance_sessions_expires_at",
        "attendance_sessions",
        ["expires_at"],
        unique=False,
    )

    op.create_index(
        "ix_attendance_sessions_faculty_id",
        "attendance_sessions",
        ["faculty_id"],
        unique=False,
    )

    op.create_index(
        "ix_attendance_sessions_is_active",
        "attendance_sessions",
        ["is_active"],
        unique=False,
    )

    op.create_index(
        op.f("ix_devices_user_id"),
        "devices",
        ["user_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - cleaned safely ###

    op.drop_index(
        op.f("ix_devices_user_id"),
        table_name="devices",
    )

    op.drop_index(
        "ix_attendance_sessions_is_active",
        table_name="attendance_sessions",
    )

    op.drop_index(
        "ix_attendance_sessions_faculty_id",
        table_name="attendance_sessions",
    )

    op.drop_index(
        "ix_attendance_sessions_expires_at",
        table_name="attendance_sessions",
    )

    op.drop_index(
        "ix_attendance_sessions_classroom_id",
        table_name="attendance_sessions",
    )

    op.alter_column(
        "attendance_sessions",
        "duration_minutes",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("10"),
    )

    op.alter_column(
        "attendance_sessions",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )

    op.drop_index(
        op.f("ix_attendance_ble_evidence_attendance_id"),
        table_name="attendance_ble_evidence",
    )

    op.add_column(
        "attendance",
        sa.Column(
            "is_locked",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.drop_index(
        op.f("ix_attendance_student_id"),
        table_name="attendance",
    )

    op.drop_index(
        op.f("ix_attendance_session_id"),
        table_name="attendance",
    )

    op.drop_index(
        op.f("ix_attendance_classroom_id"),
        table_name="attendance",
    )

    # ### end Alembic commands ###