"""add faculty action logs

Revision ID: a194d92fdfd0
Revises: e7cb618d3a8a
Create Date: 2026-01-22 00:32:15.803336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql  # retained to avoid altering imports


# revision identifiers, used by Alembic.
revision: str = 'a194d92fdfd0'
down_revision: Union[str, None] = 'e7cb618d3a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to avoid destructive operations ###
    op.create_table(
        'faculty_action_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('faculty_id', sa.Integer(), nullable=False),
        sa.Column('attendance_id', sa.Integer(), nullable=False),
        sa.Column('original_status', sa.String(length=20), nullable=False),
        sa.Column('new_status', sa.String(length=20), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['attendance_id'],
            ['attendance.id'],
            ondelete='RESTRICT',
        ),
        sa.ForeignKeyConstraint(
            ['faculty_id'],
            ['users.id'],
            ondelete='RESTRICT',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_faculty_action_logs_id'),
        'faculty_action_logs',
        ['id'],
        unique=False,
    )

    op.create_table(
        'sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('faculty_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(['faculty_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to match upgrade ###
    op.drop_table('sessions')
    op.drop_index(
        op.f('ix_faculty_action_logs_id'),
        table_name='faculty_action_logs',
    )
    op.drop_table('faculty_action_logs')
    # ### end Alembic commands ###
