"""phase5_review_metadata

Revision ID: c63cbdde1a3a
Revises: b0c7fdca0493
Create Date: 2026-06-14 16:06:31.508193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63cbdde1a3a'
down_revision: Union[str, None] = 'b0c7fdca0493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance', sa.Column('resolution_reason', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_attendance_reviewed_by_user',
        'attendance',
        'users',
        ['reviewed_by'],
        ['id'],
    )
    op.add_column('faculty_action_logs', sa.Column('resolution_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty_action_logs', 'resolution_type')
    op.drop_constraint(
        'fk_attendance_reviewed_by_user',
        'attendance',
        type_='foreignkey',
    )
    op.drop_column('attendance', 'resolution_reason')
    op.drop_column('attendance', 'reviewed_at')
    op.drop_column('attendance', 'reviewed_by')
    # ### end Alembic commands ###