# backend\alembic\versions\ce40e064a3fb_attendance_graph.py
"""attendance graph

Revision ID: ce40e064a3fb
Revises: 573d4e0aea31
Create Date: 2026-02-03 21:45:12.397841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce40e064a3fb'
down_revision: Union[str, None] = '573d4e0aea31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE:
    # Columns are introduced as nullable to allow migration on existing rows.
    # NOT NULL constraints will be enforced later once attendance creation flow is fully wired.
    op.add_column('attendance', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.add_column('attendance', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance', 'classrooms', ['classroom_id'], ['id'])
    op.create_foreign_key(None, 'attendance', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'attendance', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'session_id')
    op.drop_column('attendance', 'classroom_id')
    op.drop_column('attendance', 'student_id')
    # ### end Alembic commands ###
