"""add course registration sessions

Revision ID: d2f53c6d9fff
Revises: c63cbdde1a3a
Create Date: 2026-06-16 03:23:28.788268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f53c6d9fff'
down_revision: Union[str, None] = 'c63cbdde1a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_registration_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_registration_sessions_course_id'), 'course_registration_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_registration_sessions_faculty_id'), 'course_registration_sessions', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_course_registration_sessions_id'), 'course_registration_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_registration_sessions_id'), table_name='course_registration_sessions')
    op.drop_index(op.f('ix_course_registration_sessions_faculty_id'), table_name='course_registration_sessions')
    op.drop_index(op.f('ix_course_registration_sessions_course_id'), table_name='course_registration_sessions')
    op.drop_table('course_registration_sessions')
    # ### end Alembic commands ###
